services:
  webapp:
    build:
      context: .
    container_name: webapp
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: [ "docker/webapp.sh" ]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: webapp_db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: